name: Bug Report
description: "Report a general library issue."
labels: bug
body:
  - type: markdown
    attributes:
      value: "Before submitting your report, [please ensure your Laravel and PHP version is still supported](https://github.com/lmsqueezy/laravel/tree/main#requirements)."
  - type: input
    attributes:
      label: Lemon Squeezy for Laravel Version
      description: Provide the Lemon Squeezy for Laravel version that you are using.
      placeholder: 1.6.1
    validations:
      required: true
  - type: input
    attributes:
      label: Laravel Version
      description: Provide the Laravel version that you are using.
      placeholder: 10.4.1
    validations:
      required: true
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
      
